version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: db_sampleApi_postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  sample-api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./SampleApi/Controllers:/App/Controllers
      - ./SampleApi/Data:/App/Data
      - ./SampleApi/Dtos:/App/Dtos
      - ./SampleApi/Helpers:/App/Helpers
      - ./SampleApi/Migrations:/App/Migrations
      - ./SampleApi/Models:/App/Models
      - ./SampleApi/Properties:/App/Properties
      - ./SampleApi/Services:/App/Services
      - .env:/App/.env
      - ./SampleApi/appsettings.Development.json:/App/appsettings.Development.json
      - ./SampleApi/appsettings.json:/App/appsettings.json
      - ./SampleApi/Program.cs:/App/Program.cs
      - ./SampleApi/SampleApi.csproj:/App/SampleApi.csproj
      - /App/obj
      - /App/bin
    ports:
      - 5000:5000
    command: dotnet watch

volumes:
  db:
